config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # CRUD Restaurant

  # CREATE

  get "/restaurants/new", to: "restaurants#new"

  post '/restaurants', to: 'restaurants#create'

  # READ

  # see all restaurants

  get "/restaurants", to: "restaurants#index"

  # see one restaurant

  get "/restaurants/:id", to: 'restaurants#show', as: "restaurant"

  # UPDATE

  # form for editing a restaurant

  get "/restaurants/:id/edit", to: 'restaurants#edit', as: "edit_restaurant"

  # update a restaurant

  patch "/restaurants/:id", to: 'restaurants#update'

  # DELETE

  delete 'restaurants/:id', to: 'restaurants#destroy'

  # resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = ["Davis", "Neto"].sample
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurant_path(restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :rating, :address)
    #params.require(:model).permit(:*attrs)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheSpoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello <%= @user %></h1>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit "Enviar" %>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>Welcome to the Spoon!</h1>
<p>Some suggestions:</p>
<% @restaurants.each do |restaurant| %>
  <div>
    <%= link_to restaurant.name, restaurant_path(restaurant) %>
    <%= "*" * restaurant.rating %>
  </div>
<% end %>
<%= link_to "Add a restaurant!", restaurants_new_path %>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= "*" * @restaurant.rating %></h2>
<p><%= @restaurant.address %></p>
<%= link_to "Edit", edit_restaurant_path(@restaurant) %>
<%= link_to "Delete", restaurant_path(@restaurant), method: "delete",
      data: { confirm: "Are you sure?" } %>
<%= link_to "Back to restaurants", restaurants_path %>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>